### ISSUE TITLE
Automatic log deletion doesn't work

### ISSUE THREAD

**Issue by CySxL** [vyolit/Ve#13]
**Describe the bug:**
I have the "Automatically Delete Logs" enabled and set it to 7 Days, but I notice there are still bunches of notifications logs from 7 days ago.
![image](https://user-images.githubusercontent.com/15531137/209019269-3f100230-e911-4cf9-91da-ed8b4837b245.jpeg)
^ Writing this issue on 2022/Dec/22 ^
And you can see there are logs from Dec/11 and Dec/12 etc

**Steps to reproduce the behavior:**

1. Enable Automatically Delete Logs option

2. Set the duration as 7 days

**System information:**
- iOS version: 14.8
- Jailbreak: unc0ver 8.0.2
- Device: iPhone 11 Pro Max

**Comment by Traurige** [comment]
Hitting enter before finishing typing moment. I'm aware of that issue though and it'll be fixed with the next update. Don't know when that'll be, though.

**Comment by CySxL** [comment]
> Hitting enter before finishing typing moment. I'm aware of that issue though and it'll be fixed with the next update. Don't know when that'll be, though.

Thanks !! Glad to know it's a fixable issue. You always the best !

**Comment by vyolit** [comment]
This has been fixed and is coming with the 2.0 release.
